apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sketch-repo
spec:
  template:
    spec:
      containers:
      - name: sketch-repo
        env:
        - name: TZ
          value: America/Chicago
