apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: websketch-server
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  template:
    spec:
      containers:
      - name: websketch-server
        env:
        - name: TZ
          value: America/Chicago
