apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: websketch

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lti-db
  namespace: websketch
  labels:
    app: websketch
    component: db
    awsNodeType: EC2   # these pods require access to persistent storage
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      component: db
  template:
    metadata:
      labels:
        app: websketch
        component: db
        awsNodeType: EC2
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: lti-db-vol
        persistentVolumeClaim:
          claimName: lti-db-claim
      nodeSelector:
        nodeSpecialization: websketch
      tolerations:
      - key: "key"
        operator: "Equal"
        value: "websketch"
        effect: "PreferNoSchedule"
      containers:
      - name: lti-db
        image: docker.io/qrgnu/websketch.db-lti
        imagePullPolicy: Always
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db-root-pwd
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db-name
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db-pwd
        livenessProbe:
          exec:
            command:
              - bash
              - -c
              - mysqladmin ping -h localhost --password=$MYSQL_ROOT_PASSWORD
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          requests:
            cpu: "250m"
            memory: "0.5Gi"
          limits:
            cpu: "250m"
            memory: "0.5Gi"
        ports:
        - name: sql
          protocol: TCP
          containerPort: 3306
        volumeMounts:
        - name: lti-db-vol
          mountPath: /var/lib/mysql

---

apiVersion: v1
kind: Service
metadata:
  name: lti-db
  namespace: websketch
  labels:
    app: websketch
    component: db
spec:
  ports:
  - name: db-port
    protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    component: db
  type: ClusterIP
