apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rsyslog
  namespace: websketch
  labels:
    app: websketch
    component: syslog
    awsNodeType: EC2   # these pods require access to persistent storage
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      component: syslog
  template:
    metadata:
      labels:
        app: websketch
        component: syslog
        awsNodeType: EC2   # these pods require access to persistent storage
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: syslog-vol
        persistentVolumeClaim:
          claimName: syslog-claim
      nodeSelector:
        nodeSpecialization: websketch
      tolerations:
      - key: "key"
        operator: "Equal"
        value: "websketch"
        effect: "PreferNoSchedule"
      containers:
      - name: rsyslog
        image: docker.io/qrgnu/websketch.rsyslog
        imagePullPolicy: Always
        ports:
        - name: slog-tcp-port
          protocol: TCP
          containerPort: 514
        - name: slog-udp-port
          protocol: UDP
          containerPort: 514
        resources:
          requests:
            cpu: "250m"
            memory: "0.5Gi"
          limits:
            cpu: "250m"
            memory: "0.5Gi"
        volumeMounts:
        - name: syslog-vol
          mountPath: /logs

---

apiVersion: v1
kind: Service
metadata:
  name: rsyslog
  namespace: websketch
  labels:
    app: websketch
    component: syslog
spec:
  ports:
  - name: slog-tcp-port
    protocol: TCP
    port: 514
    targetPort: 514
  - name: slog-udp-port
    protocol: UDP
    port: 514
    targetPort: 514
  selector:
    component: syslog
  type: ClusterIP
