kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: syslog-pv
  namespace: websketch
  labels:
    app: websketch
    component: syslog
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  csi:
    driver: ebs.csi.aws.com
    fsType: xfs
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syslog-claim
  namespace: websketch
  labels:
    app: websketch
    component: syslog
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 2Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sketch-repo-pv
  namespace: websketch
  labels:
    app: websketch
    component: sketch-repo
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  csi:
    driver: ebs.csi.aws.com
    fsType: xfs
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sketch-repo-claim
  namespace: websketch
  labels:
    app: websketch
    component: sketch-repo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: lti-db-pv
  namespace: websketch
  labels:
    app: websketch
    component: db
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  csi:
    driver: ebs.csi.aws.com
    fsType: xfs
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lti-db-claim
  namespace: websketch
  labels:
    app: websketch
    component: db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 1Gi
